### ISSUE TITLE
Broken pip error - wrong packet seqence SQL

### ISSUE THREAD

**Issue by kritzware** [LouisBluhm/PyBot#102]
Database timing out essentially after no use, ~7 hours

**Comment by kritzware** [comment]
`SkowalzBot-0 (err):   File "/usr/local/lib/python3.4/dist-packages/pymysql/cursors.py", line 308, in _query
SkowalzBot-0 (err):     conn.query(q)
SkowalzBot-0 (err):   File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 820, in query
SkowalzBot-0 (err):     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
SkowalzBot-0 (err):   File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1002, in _read_query_result
SkowalzBot-0 (err):     result.read()
SkowalzBot-0 (err):   File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1285, in read
SkowalzBot-0 (err):     first_packet = self.connection._read_packet()
SkowalzBot-0 (err):   File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 953, in _read_packet
SkowalzBot-0 (err):     (packet_number, self._next_seq_id))
SkowalzBot-0 (err): pymysql.err.InternalError: Packet sequence number wrong - got 0 expected 1
SkowalzBot-0 (err): Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
SkowalzBot-0 (err): Traceback (most recent call last):
SkowalzBot-0 (err):   File "/usr/lib/python3.4/threading.py", line 1294, in _shutdown
SkowalzBot-0 (err):     t.join()
SkowalzBot-0 (err):   File "/usr/lib/python3.4/threading.py", line 1060, in join
SkowalzBot-0 (err):     self._wait_for_tstate_lock()
SkowalzBot-0 (err):   File "/usr/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
SkowalzBot-0 (err):     elif lock.acquire(block, timeout):
SkowalzBot-0 (err): KeyboardInterrupt`

**Comment by kritzware** [comment]
`pymysql.err.InternalError: Packet sequence number wrong - got 0 expected 1`
